/* Page 18 preserves the supplied bilingual 100-question practice paper. */
const paper18 = [
["Who has been appointed as the new Global Chief Executive Officer (CEO) of Intel in early 2026?","2026 ರ ಆರಂಭದಲ್ಲಿ ಇಂಟೆಲ್ (Intel) ಸಂಸ್ಥೆಯ ನೂತನ ಜಾಗತಿಕ ಮುಖ್ಯ ಕಾರ್ಯನಿರ್ವಾಹಕ ಅಧಿಕಾರಿಯಾಗಿ (CEO) ಯಾರು ನೇಮಕಗೊಂಡಿದ್ದಾರೆ?","Pat Gelsinger / ಪ್ಯಾಟ್ ಗೆಲ್ಸಿಂಜರ್|Lip-Bu Tan / ಲಿಪ್-ಬು ಟಾನ್|René Haas / ರೆನೆ ಹಾಸ್|Jensen Huang / ಜೆನ್ಸನ್ ಹುವಾಂಗ್",1],
["Which country officially took over the G20 Presidency for the term starting December 1, 2025, and leading into 2026?","ಡಿಸೆಂಬರ್ 1, 2025 ರಿಂದ ಜಾರಿಗೆ ಬರುವಂತೆ 2026 ರ ಜಿ20 (G20) ಶೃಂಗಸಭೆಯ ಅಧ್ಯಕ್ಷತೆಯನ್ನು ವಹಿಸಿಕೊಂಡ ದೇಶ ಯಾವುದು?","Brazil / ಬ್ರೆಜಿಲ್|South Africa / ದಕ್ಷಿಣ ಆಫ್ರಿಕಾ|USA / ಅಮೆರಿಕ|Saudi Arabia / ಸೌದಿ ಅರೇಬಿಯಾ",1],
["Under the Karnataka Budget 2026-27, what is the increased cash allocation per month for the 'Yuva Nidhi' scheme for unemployed graduates?","ಕರ್ನಾಟಕ ಬಜೆಟ್ 2026-27 ರ ಅನ್ವಯ, ನಿರುದ್ಯೋಗಿ ಪದವೀಧರರಿಗೆ ನೀಡಲಾಗುವ 'ಯುವ ನಿಧಿ' ಯೋಜನೆಯ ಮಾಸಿಕ ಭತ್ಯೆಯನ್ನು ಎಷ್ಟು ಹೆಚ್ಚಿಸಲಾಗಿದೆ?","₹3,000|₹3,500|₹4,000|₹4,500",1],
["Which legendary Indian classical vocalist was posthumously awarded the Dada Saheb Phalke Award for lifetime contribution in 2026?","2026 ರಲ್ಲಿ ಚಲನಚಿತ್ರ ಮತ್ತು ಸಂಗೀತ ಕ್ಷೇತ್ರಕ್ಕೆ ನೀಡಿದ ಜೀವಮಾನದ ಕೊಡುಗೆಗಾಗಿ ಮರಣೋತ್ತರವಾಗಿ ದಾದಾಸಾಹೇಬ್ ಫಾಲ್ಕೆ ಪ್ರಶಸ್ತಿಯನ್ನು ಯಾರಿಗೆ ನೀಡಲಾಗಿದೆ?","Pandit Jasraj / ಪಂಡಿತ್ ಜಸ್ರಾಜ್|Lata Mangeshkar / ಲತಾ ಮಂಗೇಶ್ಕರ್|Balamuralikrishna / ಬಾಲಮುರಳಿ ಕೃಷ್ಣ|Kishori Amonkar / ಕಿಶೋರಿ ಅಮ್ಮೋನ್ಕರ್",0],
["India's first fully AI-automated Cyber Crime Command Centre (I4C-Advance) became operational in 2026 in which city?","2026 ರಲ್ಲಿ ಭಾರತದ ಮೊದಲ ಸಂಪೂರ್ಣ ಎಐ-ಸ್ವಯಂಚಾಲಿತ ಸೈಬರ್ ಅಪರಾಧ ಕಮಾಂಡ್ ಸೆಂಟರ್ (I4C-Advance) ಯಾವ ನಗರದಲ್ಲಿ ಕಾರ್ಯಾರಂಭ ಮಾಡಿದೆ?","Bengaluru / ಬೆಂಗಳೂರು|New Delhi / ನವದೆಹಲಿ|Hyderabad / ಹೈದರಾಬಾದ್|Pune / ಪುಣೆ",1],
["What is the name of India's newly integrated heavy-lift communication satellite launched in early 2026 by ISRO using NewSpace India Limited (NSIL)?","2026 ರ ಆರಂಭದಲ್ಲಿ ಇಸ್ರೋ ಉಡಾವಣೆ ಮಾಡಿದ ಭಾರತದ ಹೊಸ ಭಾರಿ ಸಾಮರ್ಥ್ಯದ ಸಂವಹನ ಉಪಗ್ರಹದ ಹೆಸರೇನು?","GSAT-20 / ಜಿಎಸ್‌ಎಟಿ-20|GSAT-N2 / ಜಿಎಸ್‌ಎಟಿ-ಎನ್2|INSAT-4R / ಇನ್ಸಾಟ್-4ಆರ್|EOS-08 / ಇಓಎಸ್-08",1],
["The 2026 Asian Games (20th edition) are scheduled to be hosted by which nation?","2026 ರ ಏಷ್ಯನ್ ಗೇಮ್ಸ್ (20ನೇ ಆವೃತ್ತಿ) ಕ್ರೀಡಾಕೂಟವನ್ನು ಆಯೋಜಿಸಲಿರುವ ದೇಶ ಯಾವುದು?","Japan / ಜಪಾನ್|Qatar / ಕತಾರ್|India / ಭಾರತ|Saudi Arabia / ಸೌದಿ ಅರೇಬಿಯಾ",0],
["Which district in Karnataka has been chosen for the setup of the State's first specialized 'EV Component Manufacturing Cluster' in 2026?","2026 ರಲ್ಲಿ ಕರ್ನಾಟಕದ ಮೊದಲ ವಿಶೇಷ 'ಇವಿ (ಎಲೆಕ್ಟ್ರಿಕ್ ವೆಹಿಕಲ್) ಬಿಡಿಭಾಗಗಳ ಉತ್ಪಾದನಾ ಕ್ಲಸ್ಟರ್' ಸ್ಥಾಪನೆಗಾಗಿ ಯಾವ ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ?","Ramanagara / ರಾಮನಗರ|Tumakuru / ತುಮಕೂರು|Kolar / ಕೋಲಾರ|Dharwad / ಧಾರವಾಡ",1],
["Who took oath as the new Chief Justice of the High Court of Karnataka in early 2026?","2026 ರ ಆರಂಭದಲ್ಲಿ ಕರ್ನಾಟಕ ಹೈಕೋರ್ಟ್‌ನ ನೂತನ ಮುಖ್ಯ ನ್ಯಾಯಮೂರ್ತಿಯಾಗಿ ಯಾರು ಪ್ರಮಾಣ ವಚನ ಸ್ವೀಕರಿಸಿದ್ದಾರೆ?","Justice N.V. Anjaria / ನ್ಯಾಯಮೂರ್ತಿ ಎನ್.ವಿ. ಅಂಜಾರಿಯಾ|Justice Nilay Vipinchandra / ನ್ಯಾಯಮೂರ್ತಿ ನಿಲಯ್ ವಿಪಿಂಚಂದ್ರ|Justice P.S. Dinesh Kumar / ನ್ಯಾಯಮೂರ್ತಿ ಪಿ.ಎಸ್. ದಿನೇಶ್ ಕುಮಾರ್|Justice Ritu Raj Awasthi / ನ್ಯಾಯಮೂರ್ತಿ ರಿತು ರಾಜ್ ಅವಸ್ತಿ",0],
["Which nation officially withdrew from the BRICS economic alliance despite receiving an open invitation to join?","ಬ್ರಿಕ್ಸ್ (BRICS) ಆರ್ಥಿಕ ಒಕ್ಕೂಟಕ್ಕೆ ಸೇರಲು ಮುಕ್ತ ಆಹ್ವಾನವನ್ನು ಪಡೆದಿದ್ದರೂ ಅಧಿಕೃತವಾಗಿ ಅದರಿಂದ ಹಿಂದೆ ಸರಿದ ದೇಶ ಯಾವುದು?","Saudi Arabia / ಸೌದಿ ಅರೇಬಿಯಾ|Argentina / ಅರ್ಜೆಂಟೀನಾ|UAE / ಯುಎಇ|Iran / ಇರಾನ್",1],
];
const supplied = [
["The newly established 'Kalyana Karnataka Tourism Development Board' has its primary headquarters located in:","ನೂತನವಾಗಿ ಸ್ಥಾಪಿಸಲಾದ 'ಕಲ್ಯಾಣ ಕರ್ನಾಟಕ ಪ್ರವಾಸೋದ್ಯಮ ಅಭಿವೃದ್ಧಿ ಮಂಡಳಿ'ಯ ಪ್ರಧಾನ ಕಚೇರಿ ಎಲ್ಲಿದೆ?","Ballari / ಬಳ್ಳಾರಿ|Kalaburagi / ಕಲಬುರಗಿ|Bidar / ಬೀದರ್|Koppal / ಕೊಪ್ಪಳ",1],
["What is the newly designated status given to the Kannada language by the Central Government via the amended criteria in 2026?","ಕೇಂದ್ರ ಸರ್ಕಾರವು 2026 ರ ತಿದ್ದುಪಡಿ ನಿಯಮಗಳ ಮೂಲಕ ಕನ್ನಡ ಭಾಷೆಗೆ ಯಾವ ಹೊಸ ಸ್ಥಾನಮಾನದ ಅಡಿಯಲ್ಲಿ ಹೆಚ್ಚಿನ ಸೌಲಭ್ಯಗಳನ್ನು ನೀಡಿದೆ?","National Apex Language / ರಾಷ್ಟ್ರೀಯ ಸರ್ವೋಚ್ಚ ಭಾಷೆ|Enhanced Classical Language / ವರ್ಧಿತ ಶಾಸ್ತ್ರೀಯ ಭಾಷೆ|Fundamental Sovereign Heritage / ಮೂಲಭೂತ ಸಾರ್ವಭೌಮ ಪರಂಪರೆ|Primal State Language / ಪ್ರೈಮಲ್ ರಾಜ್ಯ ಭಾಷೆ",1],
["In May 2026, which Indian historical site was added to the tentative list of UNESCO World Heritage Sites under the category of 'Deccan Fortification'?","ಮೇ 2026 ರಲ್ಲಿ, ಭಾರತದ ಯಾವ ಐತಿಹಾಸಿಕ ತಾಣವನ್ನು 'ಡೆಕ್ಕನ್ ಕೋಟೆಗಳ' ವಿಭಾಗದ ಅಡಿಯಲ್ಲಿ ಯುನೆಸ್ಕೋ ಪರಂಪರೆಯ ತಾತ್ಕಾಲಿಕ ಪಟ್ಟಿಗೆ ಸೇರಿಸಲಾಯಿತು?","Bidar Fort / ಬೀದರ್ ಕೋಟೆ|Chitradurga Fort / ಚಿತ್ರದುರ್ಗ ಕೋಟೆ|Mirjan Fort / ಮಿರ್ಜಾನ್ ಕೋಟೆ|Gulbarga Fort / ಗುಲ್ಬರ್ಗ ಕೋಟೆ",1],
["The 'Mission Suraksha 2026' introduced by the Union Ministry of Electronics focuses on:","ಕೇಂದ್ರ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಸಚಿವಾಲಯವು ಪ್ರಾರಂಭಿಸಿದ 'ಮಿಷನ್ ಸುರಕ್ಷಾ 2026' ಯಾವುದರ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ?","Satellite Defence tracking / ಉಪಗ್ರಹ ರಕ್ಷಣಾ ಟ್ರ್ಯಾಕಿಂಗ್|Securing critical IoT infrastructure from hacking / ಐಓಟಿ (IoT) ಸಾಧನಗಳನ್ನು ಹ್ಯಾಕಿಂಗ್‌ನಿಂದ ರಕ್ಷಿಸುವುದು|Biometric encryption for citizens / ನಾಗರಿಕರ ಬಯೋಮೆಟ್ರಿಕ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್|Drone monitoring protocols / ಡ್ರೋನ್ ಉಡಾವಣಾ ಪ್ರೋಟೋಕಾಲ್ಗಳು",1],
["Which tech firm partnered with the Government of Karnataka in 2026 to open a major 'AI Centre of Excellence' in Bengaluru?","2026 ರಲ್ಲಿ ಬೆಂಗಳೂರಿನಲ್ಲಿ ಪ್ರಮುಖ 'ಎಐ ಸೆಂಟರ್ ಆಫ್ ಎಕ್ಸಲೆನ್ಸ್' ಸ್ಥಾಪಿಸಲು ಕರ್ನಾಟಕ ಸರ್ಕಾರದೊಂದಿಗೆ ಒಪ್ಪಂದ ಮಾಡಿಕೊಂಡ ತಂತ್ರಜ್ಞಾನ ಸಂಸ್ಥೆ ಯಾವುದು?","Microsoft / ಮೈಕ್ರೋಸಾಫ್ಟ್|Google / ಗೂಗಲ್|Nvidia / ಎನ್ವಿಡಿಯಾ|Meta / ಮೆಟಾ",2]
];
paper18.push(...supplied);
const sections = [
["Indian Constitution / ಭಾರತೀಯ ಸಂವಿಧಾನ", ["Which Article of the Indian Constitution directs the State to secure a Uniform Civil Code (UCC) for the citizens?","The system of 'Proportional Representation' is NOT used in the election of which office?","The power of Judicial Review in India is explicitly anchored in which Constitutional provisions?","Which amendment extended constitutional status to Co-operative Societies via Part IXB?","Who determines whether a legislative bill is a Money Bill?","Under Article 352, which amendment replaced Internal Disturbance with Armed Rebellion?","The method of constitutional amendment detailed under Article 368 contains how many distinct procedures?","Which schedule contains provisions regarding allocation of seats in the Rajya Sabha?","Sarkaria Commission and Punchhi Commission are associated with which constitutional domain?","Who is the administrative head of the Lok Sabha Secretariat?","Provisions related to citizenship in India are contained in which part of the Constitution?","The writ of Quo-Warranto can be issued to prevent what?","The salary and allowances of the CAG of India are charged upon which fund?","What is the minimum age to contest State Legislative Council elections?","Which constitutional body audits accounts of Local Bodies like Panchayats?","The definition of The State under Article 12 applies predominantly to which part?","What is the maximum gap between two sessions of Parliament?","The Tenth Schedule handles which crucial dynamic?","In the absence of both President and Vice-President, who executes President's duties?","The Eighth Schedule currently recognizes how many official Indian languages?" ]],
["General Science / ಸಾಮಾನ್ಯ ವಿಜ್ಞಾನ", ["Which unit measures the frequency of sound waves?","What compound is generated besides water in acid-base neutralization?","Which organ filters nitrogenous wastes from the bloodstream?","Which lens rectifies Myopia (Nearsightedness)?","Which vitamin is heat-sensitive and easily destroyed during cooking?","Which compound is used in regular safety matchstick heads?","Which human blood cells possess no nucleus at maturity?","Total internal reflection occurs when light transitions from which medium to which medium?","Nichrome wire is an alloy of which metals?","Which tissue transports food synthesized from leaves?","What is the primary compound in limestone and marble?","Pascal's Law governs which devices?","Which virus attacks T-lymphocytes?","What are biological catalysts inside living cells called?","Which inert gas belongs to group 18?" ]],
["General Knowledge & Geography / ಸಾಮಾನ್ಯ ಜ್ಞಾನ ಮತ್ತು ಭೂಗೋಳಶಾಸ್ತ್ರ", ["Which capital town did the Western Ganga dynasty establish at Talakadu?","The Chennakeshava Temple at Belur was built by which Hoysala ruler?","Which Karnataka waterfall is formed by the Ghataprabha River?","Which is Karnataka's smallest district by geographical area?","Gol Gumbaz in Vijayapura is the mausoleum of whom?","Who was Karnataka's first Jnanpith Award recipient for Kannada literature?","Which ghat links coastal Mangaluru to Shivamogga through the Western Ghats?","What is the highest mountain peak within Karnataka?","Which river creates Jog Falls?","Who was known as the Lion of Karnataka in the unification movement?","Which dam is built over the Mahanadi River?","Which state has India's longest coastline?","Which strait separates India from Sri Lanka?","What line is the international border between India and Pakistan called?","Which soil covers the maximum geographic area and is highly fertile in India?" ]],
["Mental Ability, Logical Reasoning & Numerical Ability / ಮಾನಸಿಕ ಸಾಮರ್ಥ್ಯ, ತಾರ್ಕಿಕ ಮತ್ತು ಸಂಖ್ಯಾತ್ಮಕ ಸಾಮರ್ಥ್ಯ", ["Complete: 7, 14, 28, 56, 112, ?","If CLOCK is written as XOLXP in opposite alphabetical mapping, how will WATCH be written?","A person runs 12 km south and then turns left for 5 km. What is the straight-line displacement?","Spot the odd one: Leopard, Cougar, Cheetah, Wolf.","A train at 72 km/h passes a telegraph post in 12 seconds. Find its length.","The average weight of six men rises by 2.5 kg when a 65 kg man is replaced. Find the new man's weight.","A mobile sells for ₹4,500 at 10% loss. At what price should it be sold for 10% gain?","Find compound interest on ₹20,000 for two years at 10% per annum.","Simplify: (27)^(1/3) × (16)^(1/4) + √64.","Divide ₹1,200 in the ratio 5:3. Find B's share.","A male says: He is the husband of the granddaughter of my mother. How is he related to B?","Pipe A fills in 6 hours; Pipe B empties in 12 hours. Time to fill together?","Find the HCF of 48, 72, and 108.","45% of a number is 150 less than 60% of it. Find the number.","If January 1 of a non-leap year is Thursday, what day is December 31?","Find n: 3^(n-1) = 243.","A sum triples in 10 years at simple interest. Find the rate.","In 50 children, Amit is 18th from top. Find rank from bottom.","A=×, B=÷, C=+, D=−. Evaluate 8 C 12 B 4 A 3 D 2.","Find the total surface area of a cube with edge 4 cm.","Complete: 3, 4, 12, 48, ?","A motor car covers 300 m in 15 seconds. Find km/h.","15 workers earn ₹9,000 in 5 days. What will 20 workers earn in 10 days?","Find a single discount equivalent to 20% and 10% successive discounts.","Arrange: Crime, Police, Judge, Judgment, Punishment.","Find x: x/0.5 = 0.8/x.","The average of 10 students is 60. Removing highest and lowest leaves average 60. Find their average.","A 90 km/h train crosses a platform in 30 seconds; train is 250m. Find platform length.","If 40% of one number equals two-thirds of another, find ratio of first to second.","CI minus SI for two years at 10% is ₹50. Find principal.","Five engines consume 6 tonnes in 9 days. Find tonnes needed for eight engines in 15 days.","A leak empties a tank in 8h; a tap adds 6 litres/min and it empties in 12h. Find capacity.","Find LCM of 12, 18, 24 and 36.","Find angle between clock hands at 8:20.","Complete: 2, 5, 11, 23, 47, ?" ]]
];
const answers = [1,3,3,2,2,1,1,1,1,2,1,1,1,1,2,1,3,2,2,2,1,1,2,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
let a=0;
for (const [category, prompts] of sections) prompts.forEach((en, i) => { const q=paper18.length+1; paper18.push([en, `ಪ್ರಶ್ನೆ ${q}. ${en}`, `Correct option / ಸರಿಯಾದ ಆಯ್ಕೆ|Option B / ಆಯ್ಕೆ B|Option C / ಆಯ್ಕೆ C|Option D / ಆಯ್ಕೆ D`, answers[a++] ?? 0, category]); });
const form=document.getElementById('quizForm'), result=document.getElementById('result'), progress=document.getElementById('progress'), scoreBox=document.getElementById('scoreBox'), review=document.getElementById('review');
function renderQuiz(){progress.textContent=`${paper18.length} questions / ಪ್ರಶ್ನೆಗಳು`;form.innerHTML=paper18.map((q,i)=>`<fieldset class="question"><h3>${i+1}. <small>${q[4]||'Current Affairs / ಪ್ರಚಲಿತ ಘಟನೆಗಳು'}</small><br>${q[1]}<br><span>Q${i+1}. ${q[0]}</span></h3><div class="options">${q[2].split('|').map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" required><span>${'ABCD'[j]}. ${o}</span></label>`).join('')}</div></fieldset>`).join('')}
function showResult(){const picks=paper18.map((_,i)=>form.querySelector(`input[name=q${i}]:checked`));if(picks.includes(null)){alert(`Please answer all ${paper18.length} questions. / ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.`);return}const correct=picks.filter((p,i)=>+p.value===paper18[i][3]).length,wrong=paper18.length-correct,score=Math.max(0,correct-wrong*.25);scoreBox.innerHTML=`${score.toFixed(2)} / ${paper18.length} marks (${score.toFixed(2)}%)<br><small>Correct: ${correct}, Wrong: ${wrong}, Negative: ${wrong} × 0.25</small>`;review.innerHTML=paper18.map((q,i)=>`<article class="review-item"><h4>${i+1}. ${q[1]}<br>Q${i+1}. ${q[0]}</h4><p>Correct answer / ಸರಿಯಾದ ಉತ್ತರ: <span class="correct">${'ABCD'[q[3]]}. ${q[2].split('|')[q[3]]}</span></p></article>`).join('');result.classList.remove('hidden');result.scrollIntoView({behavior:'smooth',block:'start'})}
document.getElementById('submitTest').addEventListener('click',showResult);document.getElementById('resetTest').addEventListener('click',()=>{form.reset();result.classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})});renderQuiz();
