/* Page 20: supplied bilingual questions and answers. Kannada is intentionally retained. */
const paper20 = [
["Current Affairs / ಪ್ರಚಲಿತ ಘಟನೆಗಳು", [
["Which privately developed rocket launched into orbit under Mission Aagaman?", "'ಮಿಷನ್ ಆಗಮನ್' ಅಡಿಯಲ್ಲಿ ಬಾಹ್ಯಾಕಾಶಕ್ಕೆ ಯಶಸ್ವಿಯಾಗಿ ಉಡಾವಣೆಗೊಂಡ ಭಾರತದ ಮೊದಲ ಖಾಸಗಿ ನಿರ್ಮಿತ ಆರ್ಬಿಟಲ್ ರಾಕೆಟ್ ಯಾವುದು?", "Vikram-1", "ವಿಕ್ರಮ್-1"],
["Which team won the IPL 2026 title by defeating Gujarat Titans?", "ಗುಜರಾತ್ ಟೈಟನ್ಸ್ ತಂಡವನ್ನು ಸೋಲಿಸಿ IPL 2026ರ ಪ್ರಶಸ್ತಿಯನ್ನು ಗೆದ್ದ ತಂಡ ಯಾವುದು?", "Royal Challengers Bengaluru", "ರಾಯಲ್ ಚಾಲೆಂಜರ್ಸ್ ಬೆಂಗಳೂರು"],
["India defeated which country in the Men's ICC T20 World Cup 2026 final?", "2026ರ ಪುರುಷರ ಐಸಿಸಿ ಟಿ20 ವಿಶ್ವಕಪ್ ಫೈನಲ್‌ನಲ್ಲಿ ಭಾರತ ಯಾವ ದೇಶವನ್ನು ಸೋಲಿಸಿತು?", "New Zealand", "ನ್ಯೂಜಿಲ್ಯಾಂಡ್"],
["NIMHANS launched a public sleep database for patients recovering from which condition?", "ನಿಮ್ಹಾನ್ಸ್ ಸಾರ್ವಜನಿಕ ನಿದ್ರೆಯ ಡೇಟಾಬೇಸ್ ಅನ್ನು ಯಾವ ಕಾಯಿಲೆಯಿಂದ ಚೇತರಿಸಿಕೊಳ್ಳುತ್ತಿರುವ ರೋಗಿಗಳಿಗಾಗಿ ಬಿಡುಗಡೆ ಮಾಡಿತು?", "Stroke", "ಪಾರ್ಶ್ವವಾಯು (ಸ್ಟ್ರೋಕ್)"],
["Where was Karnataka's first government-run Women's Driver Training Institute approved?", "ಕರ್ನಾಟಕದ ಮೊದಲ ಸರ್ಕಾರಿ ಸ್ವಾಮ್ಯದ ಮಹಿಳಾ ಚಾಲಕರ ತರಬೇತಿ ಸಂಸ್ಥೆಯನ್ನು ಯಾವ ಕೈಗಾರಿಕಾ ಪ್ರದೇಶದಲ್ಲಿ ಅನುಮೋದಿಸಲಾಗಿದೆ?", "Bidadi Industrial Area", "ಬಿದದಿ ಕೈಗಾರಿಕಾ ಪ್ರದೇಶ"],
["Which board announced AI-enabled Smart Water Meters under PPP?", "ಪಿಪಿಪಿ ಮಾದರಿಯಲ್ಲಿ ಎಐ-ಚಾಲಿತ ಸ್ಮಾರ್ಟ್ ವಾಟರ್ ಮೀಟರ್‌ಗಳನ್ನು ಯಾವ ಜಲಮಂಡಳಿ ಘೋಷಿಸಿತು?", "BWSSB (Bengaluru)", "ಬಿಡಬ್ಲ್ಯೂಎಸ್ಎಸ್‌ಬಿ (ಬೆಂಗಳೂರು)"],
["India was elected Vice-President of which global financial monitoring body?", "ಯಾವ ಜಾಗತಿಕ ಆರ್ಥಿಕ ಮೇಲ್ವಿಚಾರಣಾ ಸಂಸ್ಥೆಯ ಉಪಾಧ್ಯಕ್ಷ ಸ್ಥಾನಕ್ಕೆ ಭಾರತ ಆಯ್ಕೆಯಾಯಿತು?", "FATF (Financial Action Task Force)", "ಎಫ್‌ಎಟಿಎಫ್"],
["What technology did Bridge Man of India Girish Bharadwaj use for village bridges?", "ಗಿರೀಶ್ ಭಾರದ್ವಾಜ್ ಅವರು ಹಳ್ಳಿಗಳ ತೂಗುಸೇತುವೆಗಳಿಗೆ ಯಾವ ತಂತ್ರಜ್ಞಾನ ಬಳಸಿದರು?", "Low-cost eco-friendly suspension technology", "ಕಡಿಮೆ ವೆಚ್ಚದ ಪರಿಸರ ಸ್ನೇಹಿ ತೂಗುಸೇತುವೆ ತಂತ್ರಜ್ಞಾನ"],
["Who won the 2026 Women's Premier League title?", "2026ರ ಮಹಿಳಾ ಪ್ರೀಮಿಯರ್ ಲೀಗ್ ಪ್ರಶಸ್ತಿಯನ್ನು ಗೆದ್ದ ತಂಡ ಯಾವುದು?", "Royal Challengers Bengaluru", "ರಾಯಲ್ ಚಾಲೆಂಜರ್ಸ್ ಬೆಂಗಳೂರು"],
["Who was Player of the Tournament in the ICC Men's T20 World Cup 2026?", "2026ರ ಐಸಿಸಿ ಪುರುಷರ ಟಿ20 ವಿಶ್ವಕಪ್‌ನ ಸರಣಿ ಶ್ರೇಷ್ಠ ಪ್ರಶಸ್ತಿ ಪಡೆದ ಆಟಗಾರ ಯಾರು?", "Sanju Samson", "ಸಂಜು ಸ್ಯಾಮ್ಸನ್"],
["What was the 12th International Day of Yoga 2026 theme?", "12ನೇ ಅಂತರರಾಷ್ಟ್ರೀಯ ಯೋಗ ದಿನ 2026ರ ಅಧಿಕೃತ ಥೀಮ್ ಏನಿತ್ತು?", "Yoga for Healthy Ageing", "ಆರೋಗ್ಯಕರ ವೃದ್ಧಾಪ್ಯಕ್ಕಾಗಿ ಯೋಗ"],
["Which Karnataka destinations were shortlisted under Global Destination Development?", "ಜಾಗತಿಕ ಪ್ರವಾಸಿ ತಾಣ ಅಭಿವೃದ್ಧಿ ಯೋಜನೆಗೆ ಕರ್ನಾಟಕದ ಯಾವ ಸ್ಥಳಗಳು ಆಯ್ಕೆಯಾದವು?", "Hampi, Mysuru, and Lakkundi", "ಹಂಪಿ, ಮೈಸೂರು ಮತ್ತು ಲಕ್ಕುಂಡಿ"],
["Which award did Major Abhilasha Barak receive for gender equity in UN peacekeeping?", "ಯುಎನ್ ಶಾಂತಿಪಾಲನಾ ಪಡೆಗಳಲ್ಲಿ ಲಿಂಗ ಸಮಾನತೆಗಾಗಿ ಮೇಜರ್ ಅಭಿಲಾಷಾ ಬರಾಕ್ ಪಡೆದ ಪ್ರಶಸ್ತಿ ಯಾವುದು?", "UN Military Gender Advocate of the Year", "ಯುಎನ್ ಮಿಲಿಟರಿ ಜೆಂಡರ್ ಅಡ್ವೊಕೇಟ್ ಪ್ರಶಸ್ತಿ"],
["From which city was the 75th Fit India Sundays on Cycle event led?", "75ನೇ ಫಿಟ್ ಇಂಡಿಯಾ ಸಂಡೇಸ್ ಆನ್ ಸೈಕಲ್ ಕಾರ್ಯಕ್ರಮದ ನೇತೃತ್ವ ಯಾವ ನಗರದಿಂದ ಆಯಿತು?", "Ahmedabad", "ಅಹಮದಾಬಾದ್"],
["Who set a 10.09-second 100m national record at the Federation Cup?", "ಫೆಡರೇಶನ್ ಕಪ್‌ನ 100 ಮೀಟರ್‌ನಲ್ಲಿ 10.09 ಸೆಕೆಂಡುಗಳ ರಾಷ್ಟ್ರೀಯ ದಾಖಲೆ ಬರೆದವರು ಯಾರು?", "Gurindervir Singh", "ಗುರಿಂದರ್ವೀರ್ ಸಿಂಗ್"],
["India's deepest underground metro station became operational in which city?", "ಭಾರತದ ಅತ್ಯಂತ ಆಳವಾದ ಭೂಗತ ಮೆಟ್ರೋ ನಿಲ್ದಾಣ ಯಾವ ನಗರದಲ್ಲಿ ಕಾರ್ಯಾರಂಭ ಮಾಡಿತು?", "Pune (Civil Court Station)", "ಪುಣೆ (ಸಿವಿಲ್ ಕೋರ್ಟ್ ನಿಲ್ದಾಣ)"],
["Which state made registration of live-in relationships mandatory?", "ಲಿವ್-ಇನ್ ಸಂಬಂಧಗಳ ನೋಂದಣಿಯನ್ನು ಕಡ್ಡಾಯಗೊಳಿಸಿದ ರಾಜ್ಯ ಯಾವುದು?", "Uttarakhand", "ಉತ್ತರಾಖಂಡ"],
["What IP Index position did India secure in 2026?", "2026ರ ಅಂತರರಾಷ್ಟ್ರೀಯ ಬೌದ್ಧಿಕ ಆಸ್ತಿ ಸೂಚ್ಯಂಕದಲ್ಲಿ ಭಾರತದ ಸ್ಥಾನ ಎಷ್ಟು?", "42nd", "42ನೇ ಸ್ಥಾನ"],
["Which state launched the Digital Police FIR portal?", "ಡಿಜಿಟಲ್ ಪೊಲೀಸ್ ಎಫ್‌ಐಆರ್ ಪೋರ್ಟಲ್ ಆರಂಭಿಸಿದ ರಾಜ್ಯ ಯಾವುದು?", "Telangana", "ತೆಲಂಗಾಣ"],
["Which state implemented localized Heat Wave Insurance for construction workers?", "ಹೊರಾಂಗಣ ಕಟ್ಟಡ ಕಾರ್ಮಿಕರಿಗಾಗಿ ಬಿಸಿಗಾಳಿ ವಿಮೆ ಜಾರಿಗೆ ತಂದ ಮೊದಲ ರಾಜ್ಯ ಯಾವುದು?", "Telangana", "ತೆಲಂಗಾಣ"]]],
["Indian Constitution & Polity / ಭಾರತೀಯ ಸಂವಿಧಾನ", [
["Which Article defines a Money Bill?", "ಹಣಕಾಸು ಮಸೂದೆಯನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುವ ವಿಧಿ ಯಾವುದು?", "Article 110", "ವಿಧಿ 110"],["Under which Article can High Courts issue writs?", "ಹೈಕೋರ್ಟ್‌ಗಳು ಯಾವ ವಿಧಿಯ ಅಡಿಯಲ್ಲಿ ರಿಟ್‌ಗಳನ್ನು ಹೊರಡಿಸುತ್ತವೆ?", "Article 226", "ವಿಧಿ 226"],["Which amendment added the Tenth Schedule?", "10ನೇ ಅನುಸೂಚಿಯನ್ನು ಸೇರಿಸಿದ ತಿದ್ದುಪಡಿ ಯಾವುದು?", "52nd Amendment Act, 1985", "52ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ, 1985"],["Who presides over a joint sitting when Lok Sabha Speaker and Deputy Speaker are absent?", "ಲೋಕಸಭೆಯ ಸ್ಪೀಕರ್ ಮತ್ತು ಉಪಸ್ಪೀಕರ್ ಗೈರುಹಾಜರಾದಾಗ ಜಂಟಿ ಅಧಿವೇಶನದ ಅಧ್ಯಕ್ಷತೆ ಯಾರು ವಹಿಸುತ್ತಾರೆ?", "Deputy Chairman of Rajya Sabha", "ರಾಜ್ಯಸಭೆಯ ಉಪಸಭಾಪತಿ"],["Which Part covers Official Languages?", "ಅಧಿಕೃತ ಭಾಷೆಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ ಸಂವಿಧಾನದ ಭಾಗ ಯಾವುದು?", "Part XVII", "ಭಾಗ 17"],["Which amendment reduced voting age to 18?", "ಮತದಾನದ ವಯಸ್ಸನ್ನು 18ಕ್ಕೆ ಇಳಿಸಿದ ತಿದ್ದುಪಡಿ ಯಾವುದು?", "61st Amendment Act, 1988", "61ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ, 1988"],["Which Article provides for Financial Emergency?", "ಹಣಕಾಸು ತುರ್ತು ಪರಿಸ್ಥಿತಿಗೆ ಸಂಬಂಧಿಸಿದ ವಿಧಿ ಯಾವುದು?", "Article 360", "ವಿಧಿ 360"],["Finance Commission is constituted under which Article?", "ಹಣಕಾಸು ಆಯೋಗವನ್ನು ಯಾವ ವಿಧಿಯ ಅಡಿಯಲ್ಲಿ ರಚಿಸಲಾಗುತ್ತದೆ?", "Article 280", "ವಿಧಿ 280"],["Which committee recommended Fundamental Duties?", "ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳನ್ನು ಸೇರಿಸಲು ಶಿಫಾರಸು ಮಾಡಿದ ಸಮಿತಿ ಯಾವುದು?", "Swaran Singh Committee", "ಸ್ವರ್ಣ ಸಿಂಗ್ ಸಮಿತಿ"],["Who is India's First Law Officer?", "ಭಾರತದ ಮೊದಲ ಕಾನೂನು ಅಧಿಕಾರಿ ಯಾರು?", "Attorney General of India", "ಭಾರತದ ಅಟಾರ್ನಿ ಜನರಲ್"],["When did the 73rd Amendment come into force?", "73ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ ಯಾವಾಗ ಜಾರಿಗೆ ಬಂತು?", "April 24, 1993", "ಏಪ್ರಿಲ್ 24, 1993"],["How many languages are in the Eighth Schedule?", "8ನೇ ಅನುಸೂಚಿಯಲ್ಲಿ ಎಷ್ಟು ಭಾಷೆಗಳಿವೆ?", "22", "22"],["Which amendment introduced 10% EWS reservation?", "EWSಗೆ 10% ಮೀಸಲಾತಿ ನೀಡಿದ ತಿದ್ದುಪಡಿ ಯಾವುದು?", "103rd Amendment Act, 2019", "103ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ, 2019"],["Who removes a High Court judge?", "ಹೈಕೋರ್ಟ್ ನ್ಯಾಯಾಧೀಶರನ್ನು ಹುದ್ದೆಯಿಂದ ತೆಗೆದುಹಾಕುವವರು ಯಾರು?", "President after an address by Parliament", "ಸಂಸತ್ತಿನ ನಿರ್ಣಯದ ನಂತರ ರಾಷ್ಟ್ರಪತಿಗಳು"],["Minimum age to contest President's election?", "ರಾಷ್ಟ್ರಪತಿ ಚುನಾವಣೆಗೆ ಸ್ಪರ್ಧಿಸಲು ಕನಿಷ್ಠ ವಯಸ್ಸು ಎಷ್ಟು?", "35 years", "35 ವರ್ಷ"],["DPSP was borrowed from which country?", "ರಾಜ್ಯ ನಿರ್ದೇಶಕ ತತ್ವಗಳನ್ನು ಯಾವ ದೇಶದಿಂದ ಪಡೆಯಲಾಗಿದೆ?", "Ireland", "ಐರ್ಲೆಂಡ್"],["Which Article abolishes untouchability?", "ಅಸ್ಪೃಶ್ಯತೆಯನ್ನು ರದ್ದುಗೊಳಿಸುವ ವಿಧಿ ಯಾವುದು?", "Article 17", "ವಿಧಿ 17"],["Who is final interpreter of the Constitution?", "ಸಂವಿಧಾನದ ಅಂತಿಮ ವ್ಯಾಖ್ಯಾನಕಾರ ಯಾರು?", "Supreme Court of India", "ಭಾರತದ ಸುಪ್ರೀಂ ಕೋರ್ಟ್"],["When was the Preamble amended?", "ಪೀಠಿಕೆಯನ್ನು ಯಾವ ವರ್ಷದಲ್ಲಿ ತಿದ್ದುಪಡಿ ಮಾಡಲಾಯಿತು?", "1976 (42nd Amendment)", "1976 (42ನೇ ತಿದ್ದುಪಡಿ)"],["Who appoints UPSC Chairperson and members?", "ಯುಪಿಎಸ್‌ಸಿ ಅಧ್ಯಕ್ಷರು ಮತ್ತು ಸದಸ್ಯರನ್ನು ಯಾರು ನೇಮಕ ಮಾಡುತ್ತಾರೆ?", "President of India", "ಭಾರತದ ರಾಷ್ಟ್ರಪತಿ"]]],
["Karnataka GK, History & Geography / ಕರ್ನಾಟಕ ಜಿಕೆ, ಇತಿಹಾಸ ಮತ್ತು ಭೂಗೋಳ", [
["Founder of the Kadamba Dynasty?","ಕದಂಬ ಮನೆತನದ ಸ್ಥಾಪಕ ಯಾರು?","Mayurasharma","ಮಯೂರಶರ್ಮ"],["Halmidi inscription belongs to which century?","ಹಲ್ಮಿಡಿ ಶಾಸನವು ಯಾವ ಶತಮಾನಕ್ಕೆ ಸೇರಿದೆ?","5th Century AD","ಕ್ರಿ.ಶ. 5ನೇ ಶತಮಾನ"],["Who authored Kavirajamarga?","ಕವಿರಾಜಮಾರ್ಗವನ್ನು ರಚಿಸಿದವರು ಯಾರು?","Amoghavarsha I (Nrupatunga)","ಅಮೋಘವರ್ಷ ನೃಪತುಂಗ"],["When was Mysore State renamed Karnataka?","ಮೈಸೂರು ರಾಜ್ಯವನ್ನು ಕರ್ನಾಟಕ ಎಂದು ಯಾವಾಗ ಮರುನಾಮಕರಣ ಮಾಡಲಾಯಿತು?","November 1, 1973","ನವೆಂಬರ್ 1, 1973"],["Cradle of Indian Temple Architecture?","ಭಾರತೀಯ ದೇವಾಲಯ ವಾಸ್ತುಶಿಲ್ಪದ ತೊಟ್ಟಿಲು ಯಾವುದು?","Aihole","ಐಹೊಳೆ"],["When was the Battle of Talikota?","ತಾಳಿಕೋಟೆ ಕದನ ನಡೆದ ವರ್ಷ ಯಾವುದು?","1565 AD","ಕ್ರಿ.ಶ. 1565"],["Karnataka woman who led an 1824 revolt?","1824ರ ಬ್ರಿಟಿಷ್ ವಿರೋಧಿ ಸಶಸ್ತ್ರ ಬಂಡಾಯದ ನಾಯಕಿ ಯಾರು?","Kittur Rani Chennamma","ಕಿತ್ತೂರು ರಾಣಿ ಚೆನ್ನಮ್ಮ"],["Highest peak in Karnataka?","ಕರ್ನಾಟಕದ ಅತ್ಯಂತ ಎತ್ತರವಾದ ಶಿಖರ ಯಾವುದು?","Mullayanagiri","ಮುಳ್ಳಯ್ಯನಗಿರಿ"],["Which river forms Jog Falls?","ಜೋಗ ಜಲಪಾತವನ್ನು ಸೃಷ್ಟಿಸುವ ನದಿ ಯಾವುದು?","Sharavathi River","ಶರಾವತಿ ನದಿ"],["Chief architect of Vidhana Soudha?","ವಿಧಾನಸೌಧದ ಪ್ರಮುಖ ರೂವಾರಿ ಯಾರು?","Kengal Hanumanthaiah","ಕೆಂಗಲ್ ಹನುಮಂತಯ್ಯ"],["Lowest literacy district in Karnataka?","ಕರ್ನಾಟಕದಲ್ಲಿ ಅತಿ ಕಡಿಮೆ ಸಾಕ್ಷರತಾ ಪ್ರಮಾಣದ ಜಿಲ್ಲೆ ಯಾವುದು?","Yadgir","ಯಾದಗಿರಿ"],["Where is Suvarna Vidhana Soudha?","ಸುವರ್ಣ ವಿಧಾನಸೌಧ ಎಲ್ಲಿದೆ?","Belagavi","ಬೆಳಗಾವಿ"],["Lifeline of Mandya and Mysuru?","ಮಂಡ್ಯ ಮತ್ತು ಮೈಸೂರು ಜಿಲ್ಲೆಗಳ ಜೀವನದಿ ಯಾವುದು?","Kaveri River","ಕಾವೇರಿ ನದಿ"],["First Kannada Jnanpith winner in 1967?","1967ರ ಮೊದಲ ಕನ್ನಡ ಜ್ಞಾನಪೀಠ ಪುರಸ್ಕೃತ ಯಾರು?","Kuvempu","ಕುವೆಂಪು"],["Bandipur National Park is in which district?","ಬಂಡೀಪುರ ರಾಷ್ಟ್ರೀಯ ಉದ್ಯಾನವನ ಯಾವ ಜಿಲ್ಲೆಯಲ್ಲಿದೆ?","Chamarajanagar","ಚಾಮರಾಜನಗರ"],["Founder of Hoysala Dynasty?","ಹೊಯ್ಸಳ ರಾಜವಂಶದ ಸ್ಥಾಪಕ ಯಾರು?","Nripa Kama / Sala","ನೃಪಕಾಮ / ಸಳ"],["Vidurashwatha Incident occurred in which district?","ವಿದುರಾಶ್ವತ್ಥ ಘಟನೆ ಯಾವ ಜಿಲ್ಲೆಯಲ್ಲಿದೆ?","Chikkaballapura","ಚಿಕ್ಕಬಳ್ಳಾಪುರ"],["Coffee Capital of India?","ಭಾರತದ ಕಾಫಿ ರಾಜಧಾನಿ ಎಂದು ಕರೆಯುವ ಜಿಲ್ಲೆ ಯಾವುದು?","Kodagu","ಕೊಡಗು"],["Vatapi is in which present-day district?","ವಾತಾಪಿ ಈಗಿನ ಯಾವ ಜಿಲ್ಲೆಯಲ್ಲಿದೆ?","Bagalkote","ಬಾಗಲಕೋಟೆ"],["Who composed Udayavagali Namma Cheluva Kannada Nadu?","ಉದಯವಾಗಲಿ ನಮ್ಮ ಚೆಲುವ ಕನ್ನಡ ನಾಡು ರಚಿಸಿದವರು ಯಾರು?","Huilgol Narayana Rao","ಹುಯಿಲಗೋಳ ನಾರಾಯಣ ರಾವ್"],["Pass connecting Mangaluru and Bengaluru?","ಮಂಗಳೂರು ಮತ್ತು ಬೆಂಗಳೂರನ್ನು ಸಂಪರ್ಕಿಸುವ ಘಾಟ್ ಯಾವುದು?","Shiradi Ghat","ಶಿರಾಡಿ ಘಾಟ್"],["Karnataka's 31st district?","ಕರ್ನಾಟಕದ 31ನೇ ಹೊಸ ಜಿಲ್ಲೆ ಯಾವುದು?","Vijayanagara","ವಿಜಯನಗರ"],["Pitamaha of Carnatic Music?","ಕರ್ನಾಟಕ ಸಂಗೀತದ ಪಿತಾಮಹ ಯಾರು?","Purandara Dasa","ಪುರಂದರದಾಸ"],["Karnataka coastline length?","ಕರ್ನಾಟಕದ ಕರಾವಳಿ ತೀರದ ಉದ್ದ ಎಷ್ಟು?","320 km","320 ಕಿಮೀ"],["Leaders of Halagali Bedas revolt?","ಹಲಗಲಿಯ ಬೇಡರ ದಂಗೆಯ ನಾಯಕರು ಯಾರು?","Jadaga and Balya","ಜಡಗ ಮತ್ತು ಬಾಲ್ಯ"]]],
["General Science / ಸಾಮಾನ್ಯ ವಿಜ್ಞಾನ", [
["Functional unit of kidney?","ಮೂತ್ರಪಿಂಡದ ಕಾರ್ಯಾತ್ಮಕ ಘಟಕ ಯಾವುದು?","Nephron","ನೆಫ್ರಾನ್"],["Gas responsible for ozone depletion?","ಓಝೋನ್ ಪದರದ ಸವಕಳಿಗೆ ಕಾರಣವಾಗುವ ಅನಿಲ ಯಾವುದು?","Chlorofluorocarbons (CFCs)","ಕ್ಲೋರೋಫ್ಲೋರೋಕಾರ್ಬನ್‌ಗಳು"],["SI unit of electric current?","ವಿದ್ಯುತ್ ಪ್ರವಾಹದ SI ಏಕಮಾನ ಯಾವುದು?","Ampere","ಆಂಪಿಯರ್"],["Ascorbic acid is which vitamin?","ಆಸ್ಕೋರ್ಬಿಕ್ ಆಮ್ಲ ಯಾವ ಜೀವಸತ್ವ?","Vitamin C","ವಿಟಮಿನ್ ಸಿ"],["Best conductor of electricity?","ಅತ್ಯುತ್ತಮ ವಿದ್ಯುತ್ ವಾಹಕ ಲೋಹ ಯಾವುದು?","Silver","ಬೆಳ್ಳಿ"],["Insulin deficiency causes which disease?","ಇನ್ಸುಲಿನ್ ಕೊರತೆಯಿಂದ ಉಂಟಾಗುವ ಕಾಯಿಲೆ ಯಾವುದು?","Diabetes Mellitus","ಮಧುಮೇಹ"],["Mirror used in vehicle headlights?","ವಾಹನದ ಹೆಡ್‌ಲೈಟ್‌ಗಳಲ್ಲಿ ಬಳಸುವ ದರ್ಪಣ ಯಾವುದು?","Concave Mirror","ನಿಮ್ನ ದರ್ಪಣ"],["Primary constituent of CNG?","ನೈಸರ್ಗಿಕ ಅನಿಲದ ಪ್ರಮುಖ ಘಟಕ ಯಾವುದು?","Methane","ಮಿಥೇನ್"],["Sound cannot travel through?","ಶಬ್ದ ತರಂಗಗಳು ಯಾವುದರ ಮೂಲಕ ಚಲಿಸಲಾರವು?","Vacuum","ಶೂನ್ಯಪ್ರದೇಶ"],["Universal recipient blood group?","ಸಾರ್ವತ್ರಿಕ ಸ್ವೀಕರಿಸುವ ರಕ್ತದ ಗುಂಪು ಯಾವುದು?","AB Positive (AB+)","ಎಬಿ ಪಾಸಿಟಿವ್"],["Liquid to vapor below boiling point?","ಕುದಿಯುವ ಬಿಂದುಗಿಂತ ಕೆಳಗೆ ದ್ರವವು ಆವಿಯಾಗುವ ಪ್ರಕ್ರಿಯೆ ಯಾವುದು?","Evaporation","ಬಾಷ್ಪೀಕರಣ"],["Formula of table salt?","ಅಡುಗೆ ಉಪ್ಪಿನ ರಾಸಾಯನಿಕ ಸೂತ್ರವೇನು?","NaCl (Sodium Chloride)","NaCl (ಸೋಡಿಯಂ ಕ್ಲೋರೈಡ್)"],["Tissue transporting water from roots?","ಬೇರುಗಳಿಂದ ಎಲೆಗಳಿಗೆ ನೀರು ಸಾಗಿಸುವ ಅಂಗಾಂಶ ಯಾವುದು?","Xylem","ಝೈಲಂ"],["Instrument measuring atmospheric pressure?","ವಾತಾವರಣದ ಒತ್ತಡವನ್ನು ಅಳೆಯುವ ಸಾಧನ ಯಾವುದು?","Barometer","ಬಾರೋಮೀಟರ್"],["Green leaf pigment?","ಎಲೆಗಳಿಗೆ ಹಸಿರು ಬಣ್ಣ ನೀಡುವ ವರ್ಣದ್ರವ್ಯ ಯಾವುದು?","Chlorophyll","ಕ್ಲೋರೋಫಿಲ್"]]],
["Mental Ability, Logical Reasoning & Numerical Ability / ಮಾನಸಿಕ ಸಾಮರ್ಥ್ಯ ಮತ್ತು ಗಣಿತ", [
["Next number: 3, 7, 15, 31, 63, ?","3, 7, 15, 31, 63 ಸರಣಿಯ ಮುಂದಿನ ಸಂಖ್ಯೆ ಯಾವುದು?","127","127"],["If TRAIN is WUDLQ, how is BUS coded?","TRAIN ಅನ್ನು WUDLQ ಎಂದರೆ BUS ಸಂಕೇತ ಏನು?","EXV","EXV"],["Distance after 12 km north and 5 km east?","12 ಕಿಮೀ ಉತ್ತರ ಮತ್ತು 5 ಕಿಮೀ ಪೂರ್ವ ನಡೆದರೆ ನೇರ ದೂರ ಎಷ್ಟು?","13 km","13 ಕಿಮೀ"],["Odd one out: 27, 64, 125, 144, 216?","27, 64, 125, 144, 216ರಲ್ಲಿ ಭಿನ್ನವಾದ ಸಂಖ್ಯೆ ಯಾವುದು?","144","144"],["Teacher's age if 20 students average 15 and 21 persons average 16?","20 ವಿದ್ಯಾರ್ಥಿಗಳ ಸರಾಸರಿ 15 ಮತ್ತು ಶಿಕ್ಷಕರೊಂದಿಗೆ 21 ಜನರ ಸರಾಸರಿ 16 ಆದರೆ ಶಿಕ್ಷಕರ ವಯಸ್ಸು ಎಷ್ಟು?","36 years","36 ವರ್ಷ"],["Net profit after 20% markup and 10% discount?","20% ಹೆಚ್ಚಿಸಿ 10% ರಿಯಾಯಿತಿ ನೀಡಿದ ನಿವ್ವಳ ಲಾಭ ಎಷ್ಟು?","8% profit","8% ಲಾಭ"],["Annual simple-interest rate if money doubles in 8 years?","ಸರಳ ಬಡ್ಡಿಯಲ್ಲಿ 8 ವರ್ಷದಲ್ಲಿ ಹಣ ದ್ವಿಗುಣವಾದರೆ ಬಡ್ಡಿದರ ಎಷ್ಟು?","12.5%","12.5%"],["If A:B=2:3 and B:C=4:5, find A:B:C.","A:B=2:3 ಮತ್ತು B:C=4:5 ಆದರೆ A:B:C ಎಷ್ಟು?","8:12:15","8:12:15"],["Time for a 200m train at 72 km/h to pass a post?","72 ಕಿಮೀ/ಗಂ ವೇಗದ 200ಮೀ ರೈಲು ಕಂಬ ದಾಟಲು ಬೇಕಾದ ಸಮಯ?","10 seconds","10 ಸೆಕೆಂಡ್"],["Solve √625 ÷ 5 + 12.","√625 ÷ 5 + 12 ಪರಿಹರಿಸಿ.","17","17"],["Angle at 3:00?","3:00 ಗಂಟೆಗೆ ಮುಳ್ಳುಗಳ ನಡುವಿನ ಕೋನ ಎಷ್ಟು?","90°","90°"],["LCM of 12, 18, 24?","12, 18, 24ರ ಲ.ಸಾ.ಅ ಎಷ್ಟು?","72","72"],["Number when 25% plus 75 equals itself?","ಒಂದು ಸಂಖ್ಯೆಯ 25%ಗೆ 75 ಸೇರಿಸಿದರೆ ಅದೇ ಸಂಖ್ಯೆ; ಸಂಖ್ಯೆ ಯಾವುದು?","100","100"],["CI rate: ₹1,000 becomes ₹1,331 in 3 years.","₹1,000 ಮೂರು ವರ್ಷಗಳಲ್ಲಿ ₹1,331 ಆದರೆ ಚಕ್ರಬಡ್ಡಿ ದರ ಎಷ್ಟು?","10%","10%"],["If Friday is the 3rd, what day is the 27th?","3ನೇ ದಿನ ಶುಕ್ರವಾರವಾದರೆ 27ನೇ ದಿನ ಯಾವ ವಾರ?","Monday","ಸೋಮವಾರ"],["x if 3^(x−1)=81?","3^(x−1)=81 ಆದರೆ x ಎಷ್ಟು?","5","5"],["Days for 10 men if 8 men complete work in 20 days?","8 ಜನರು 20 ದಿನಗಳಲ್ಲಿ ಕೆಲಸ ಮುಗಿಸಿದರೆ 10 ಜನರು ಎಷ್ಟು ದಿನಗಳಲ್ಲಿ?","16 days","16 ದಿನ"],["HCF of 24, 36, 60?","24, 36, 60ರ ಮ.ಸಾ.ಅ ಎಷ್ಟು?","12","12"],["Find n: 2^n × 2^3 = 64.","2^n × 2^3 = 64 ಆದರೆ n ಎಷ್ಟು?","3","3"],["A is B's sister; C is B's mother; D is C's father. A is D's?","A, Bಯ ಸಹೋದರಿ; C, Bಯ ತಾಯಿ; D, Cಯ ತಂದೆ. A, Dಗೆ ಏನಾಗಬೇಕು?","Granddaughter","ಮೊಮ್ಮಗಳು"]]]
];
// The supplied Paper 20 choices. Each item is English / Kannada, and option A is the answer key.
const suppliedOptions = [
["Vikram-1 / ವಿಕ್ರಮ್-1","Agnikul-2 / ಅಗ್ನಿಕುಲ್-2","Skyroot Prime / ಸ್ಕೈರೂಟ್ ಪ್ರೈಮ್","SSLV-D3 / ಎಸ್‌ಎಸ್‌ಎಲ್‌ವಿ-ಡಿ3"],
["Royal Challengers Bengaluru / ರಾಯಲ್ ಚಾಲೆಂಜರ್ಸ್ ಬೆಂಗಳೂರು","Chennai Super Kings / ಚೆನ್ನೈ ಸೂಪರ್ ಕಿಂಗ್ಸ್","Mumbai Indians / ಮುಂಬೈ ಇಂಡಿಯನ್ಸ್","Kolkata Knight Riders / ಕೋಲ್ಕತಾ ನೈಟ್ ರೈಡರ್ಸ್"],
["New Zealand / ನ್ಯೂಜಿಲ್ಯಾಂಡ್","England / ಇಂಗ್ಲೆಂಡ್","South Africa / ದಕ್ಷಿಣ ಆಫ್ರಿಕಾ","Australia / ಆಸ್ಟ್ರೇಲಿಯಾ"],
["Stroke / ಪಾರ್ಶ್ವವಾಯು (ಸ್ಟ್ರೋಕ್)","Alzheimer's / ಆಲ್ಝೈಮರ್ಸ್","Parkinson's / ಪಾರ್ಕಿನ್ಸನ್ಸ್","Epilepsy / ಅಪಸ್ಮಾರ (ಫಿಟ್ಸ್)"],
["Bidadi Industrial Area / ಬಿದದಿ ಕೈಗಾರಿಕಾ ಪ್ರದೇಶ","Peenya Industrial Area / ಪೀಣ್ಯ ಕೈಗಾರಿಕಾ ಪ್ರದೇಶ","Baikampady / ಬೈಕಂಪಾಡಿ","Narasapura / ನರಸಾಪುರ"],
["BWSSB (Bengaluru) / ಬಿಡಬ್ಲ್ಯೂಎಸ್ಎಸ್‌ಬಿ (ಬೆಂಗಳೂರು)","KUWSDB / ಕೆಉಡಬ್ಲ್ಯೂಎಸ್‌ಡಿಬಿ","Mysuru City Corporation / ಮೈಸೂರು ಮಹಾನಗರ ಪಾಲಿಕೆ","Hubballi-Dharwad Water Board / ಹುಬ್ಬಳ್ಳಿ-ಧಾರವಾಡ ಜಲಮಂಡಳಿ"],
["FATF (Financial Action Task Force) / ಎಫ್‌ಎಟಿಎಫ್","Interpol / ಇಂಟರ್‌ಪೋಲ್","World Bank Group / ವಿಶ್ವ ಬ್ಯಾಂಕ್","IMF / ಐಎಂಎಫ್"],
["Low-cost eco-friendly suspension technology / ಕಡಿಮೆ ವೆಚ್ಚದ ತೂಗುಸೇತುವೆ ತಂತ್ರಜ್ಞಾನ","Pre-stressed Concrete Girders / ಪ್ರಿ-ಸ್ಟ್ರೆಸ್ಡ್ ಕಾಂಕ್ರೀಟ್","Bamboo Fiber Cable Mesh / ಬಿದಿರಿನ ಕೇಬಲ್ ಫೈಬರ್","Floating Pontoon Modulars / ಫ್ಲೋಟಿಂಗ್ ಪಾಂಟೂನ್"],
["Royal Challengers Bengaluru / ರಾಯಲ್ ಚಾಲೆಂಜರ್ಸ್ ಬೆಂಗಳೂರು","Delhi Capitals / ಡೆಲ್ಲಿ ಕ್ಯಾಪಿಟಲ್ಸ್","Mumbai Indians / ಮುಂಬೈ ಇಂಡಿಯನ್ಸ್","Gujarat Giants / ಗುಜರಾತ್ ಜೈಂಟ್ಸ್"],
["Sanju Samson / ಸಂಜು ಸ್ಯಾಮ್ಸನ್","Jasprit Bumrah / ಜಸ್‌ಪ್ರೀತ್ ಬುಮ್ರಾ","Hardik Pandya / ಹಾರ್ದಿಕ್ ಪಾಂಡ್ಯ","Suryakumar Yadav / ಸೂರ್ಯಕುಮಾರ್ ಯಾದವ್"],
["Yoga for Healthy Ageing / ಆರೋಗ್ಯಕರ ವೃದ್ಧಾಪ್ಯಕ್ಕಾಗಿ ಯೋಗ","Yoga for One Earth, One Family / ಒಂದೇ ಭೂಮಿ, ಒಂದೇ ಕುಟುಂಬಕ್ಕಾಗಿ ಯೋಗ","Yoga for Women Empowerment / ಮಹಿಳಾ ಸಬಲೀಕರಣಕ್ಕಾಗಿ ಯೋಗ","Yoga for Global Peace / ಜಾಗತಿಕ ಶಾಂತಿಗಾಗಿ ಯೋಗ"],
["Hampi, Mysuru, and Lakkundi / ಹಂಪಿ, ಮೈಸೂರು ಮತ್ತು ಲಕ್ಕುಂಡಿ","Badami, Pattadakal, and Aihole / ಬಾದಾಮಿ, ಪಟ್ಟದಕಲ್ಲು ಮತ್ತು ಐಹೊಳೆ","Belur, Halebidu, and Somanathapura / ಬೇಲೂರು, ಹಳೇಬೀಡು ಮತ್ತು ಸೋಮನಾಥಪುರ","Gokarna, Murudeshwar, and Udupi / ಗೋಕರ್ಣ, ಮುರುಡೇಶ್ವರ ಮತ್ತು ಉಡುಪಿ"],
["UN Military Gender Advocate of the Year / ಯುಎನ್ ಮಿಲಿಟರಿ ಜೆಂಡರ್ ಅಡ್ವೊಕೇಟ್ ಪ್ರಶಸ್ತಿ","UNESCO Peace Medal / ಯುನೆಸ್ಕೋ ಶಾಂತಿ ಪದಕ","Global Valor Cross / ಗ್ಲೋಬಲ್ ವ್ಯಾಲರ್ ಕ್ರಾಸ್","Dag Hammarskjöld Medal / ಡಾಗ್ ಹ್ಯಾಮರ್‌ಶೋಲ್ಡ್ ಪದಕ"],
["Ahmedabad / ಅಹಮದಾಬಾದ್","Bengaluru / ಬೆಂಗಳೂರು","New Delhi / ನವದೆಹಲಿ","Chandigarh / ಚಂಡೀಗಢ"],
["Gurindervir Singh / ಗುರಿಂದರ್ವೀರ್ ಸಿಂಗ್","Amlan Borgohain / ಅಮಲನ್ ಬೊರ್ಗೊಹೈನ್","Manikanta Hoblidhar / ಮಣಿಕಂಠ ಹೊಬ್ಲಿಧರ್","Muhammed Anas / ಮುಹಮ್ಮದ್ ಅನಸ್"],
["Pune (Civil Court Station) / ಪುಣೆ (ಸಿವಿಲ್ ಕೋರ್ಟ್ ನಿಲ್ದಾಣ)","Kolkata / ಕೋಲ್ಕತಾ","Mumbai / ಮುಂಬೈ","Delhi / ದೆಹಲಿ"],
["Uttarakhand / ಉತ್ತರಾಖಂಡ","Himachal Pradesh / ಹಿಮಾಚಲ ಪ್ರದೇಶ","Assam / ಅಸ್ಸಾಂ","Gujarat / ಗುಜರಾತ್"],
["42nd / 42ನೇ ಸ್ಥಾನ","38th / 38ನೇ ಸ್ಥಾನ","51st / 51ನೇ ಸ್ಥಾನ","45th / 45ನೇ ಸ್ಥಾನ"],
["Telangana / ತೆಲಂಗಾಣ","Karnataka / ಕರ್ನಾಟಕ","Kerala / ಕೇರಳ","Andhra Pradesh / ಆಂಧ್ರಪ್ರದೇಶ"],
["Telangana / ತೆಲಂಗಾಣ","Rajasthan / ರಾಜಸ್ಥಾನ","Maharashtra / ಮಹಾರಾಷ್ಟ್ರ","Gujarat / ಗುಜರಾತ್"]
];
const form = document.getElementById('quizForm');
const result = document.getElementById('result');
const progress = document.getElementById('progress');
const scoreBox = document.getElementById('scoreBox');
const review = document.getElementById('review');
const quizQuestions = [];
let number = 0;
form.innerHTML = paper20.map(([section, questions]) => `<section class="paper-section"><h3>${section}</h3>${questions.map(([en, kn, answerEn, answerKn], questionIndex) => {
  const localChoices = questions.filter((_, index) => index !== questionIndex).map(([, , enAnswer, knAnswer]) => `${enAnswer} / ${knAnswer}`);
  const options = suppliedOptions[number] || [`${answerEn} / ${answerKn}`, ...localChoices.filter(choice => choice !== `${answerEn} / ${answerKn}`).slice(0, 3)];
  const questionNumber = number;
  number += 1;
  quizQuestions.push({ en, kn, options, answer: 0 });
  return `<fieldset class="question paper20-question"><legend>${questionNumber + 1}. ${en}<br><span lang="kn">ಪ್ರಶ್ನೆ ${questionNumber + 1}. ${kn}</span></legend><div class="options">${options.map((option, optionNumber) => `<label class="option"><input type="radio" name="q${questionNumber}" value="${optionNumber}" required><span><strong>${'ABCD'[optionNumber]})</strong> ${option}</span></label>`).join('')}</div></fieldset>`;
}).join('')}</section>`).join('');
progress.textContent = `${number} questions / ಪ್ರಶ್ನೆಗಳು`;

function showResult() {
  const picks = quizQuestions.map((_, index) => form.querySelector(`input[name="q${index}"]:checked`));
  if (picks.includes(null)) {
    alert(`Please answer all ${quizQuestions.length} questions. / ದಯವಿಟ್ಟು ಎಲ್ಲಾ ${quizQuestions.length} ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.`);
    return;
  }
  const correct = picks.filter((pick, index) => Number(pick.value) === quizQuestions[index].answer).length;
  const wrong = quizQuestions.length - correct;
  const score = Math.max(0, correct - wrong * 0.25);
  scoreBox.innerHTML = `${score.toFixed(2)} / ${quizQuestions.length} marks<br><small>Correct / ಸರಿ: ${correct}; Wrong / ತಪ್ಪು: ${wrong}; Negative / ಋಣಾತ್ಮಕ: ${wrong} × 0.25</small>`;
  review.innerHTML = quizQuestions.map((question, index) => `<article class="review-item"><h4>${index + 1}. ${question.en}<br><span lang="kn">ಪ್ರಶ್ನೆ ${index + 1}. ${question.kn}</span></h4><p>Correct answer / ಸರಿಯಾದ ಉತ್ತರ: <span class="correct">A) ${question.options[question.answer]}</span></p></article>`).join('');
  result.classList.remove('hidden');
  result.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

document.getElementById('submitTest').addEventListener('click', showResult);
document.getElementById('resetTest').addEventListener('click', () => {
  form.reset();
  result.classList.add('hidden');
  window.scrollTo({ top: 0, behavior: 'smooth' });
});
